// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vanilla.Data;

#nullable disable

namespace Vanilla.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250812191626_SeedDeterministic")]
    partial class SeedDeterministic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Vanilla.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<short>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Vanilla.Models.TableEntity", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Masa 1"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Masa 2"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Masa 3"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "Masa 4"
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "Masa 5"
                        },
                        new
                        {
                            Id = (short)6,
                            Name = "Masa 6"
                        },
                        new
                        {
                            Id = (short)7,
                            Name = "Masa 7"
                        },
                        new
                        {
                            Id = (short)8,
                            Name = "Masa 8"
                        });
                });

            modelBuilder.Entity("Vanilla.Models.Reservation", b =>
                {
                    b.HasOne("Vanilla.Models.TableEntity", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Vanilla.Models.TableEntity", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
